import React from 'react'
export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div className='container text-center'>
        <h3>This is About Page</h3>
    </div>
  )
}

export default AboutPage