import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import { Header } from "./components/Header";
// import "./bootstrap.min.css";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });
import UserContext from "../app/context/UserContext.jsx";
import toast, { Toaster } from "react-hot-toast";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserContext>
      <html lang="en">
        <body className={inter.className} d-flex flex-column min-vh-100>
          <Header />
          <main className="container">
            <Toaster />
            {children}
          </main>
          <Footer />
          <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
            crossOrigin="anonymous"
          ></script>
        </body>
      </html>
    </UserContext>
  );
}
