import React from "react";
import SidebarPage from "./sidebar/page";
export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
const DashboardLayout = ({ children }) => {
  return (
    <div className="container d-flex ">
      <SidebarPage />
     <main className="mt-2 ps-5">
        {children}
     </main>
    </div>
  );
};

export default DashboardLayout;
